### ISSUE TITLE
Write instructions for final project

### ISSUE THREAD

**Issue by soungalo** [yoavram/Py4Life#20]

**Comment by yoavram** [comment]
- examples: http://f1000.com/posters/browse
- sections: abstract, method, results, summary/discussion, references
- figures / tables as appropriate
- submission - one week after presentation: PDF of poster + IPython notebook of code with explanations and instructions + data file if applicable so that we can run the notebook
- abstract submission: 1st May, one page PDF explaining background, method and data (if applicable)
- consult your adviser! ask them about money for the poster
- printing - Speedograph (03-546-1604), Copy Center (http://www.copy-center-ta.co.il/)
- grading: research problem shouldn't be trivial; presentation; code readability and clarity; code efficiency (in terms of what we learned in the course); using the right tools.
- ask questions early!

**Comment by soungalo** [comment]
Shared a preliminary version through our dropbox. Please review.

**Comment by yoavram** [comment]
My dropbox is full so I can't update files there. I send you the reviewed version of the file.

**Comment by soungalo** [comment]
Looks fine to me. I think we can upload the instructions to a new tab in the website.
Also, let's add the submission dates to the lectures page.

**Comment by yoavram** [comment]
let's make a new tab called "project" and have everything there? the submissions dates can also be on the admin tab - I don't think they are relevant to the lectures tab.
want to send me the final doc and I'll do the HTMLing?

**Comment by yoavram** [comment]
Closed by commit c1c522b
