### ISSUE TITLE
Lecture 4 for next year

### ISSUE THREAD

**Issue by yoavram** [yoavram/Py4Life#26]
Changes that should be made for next year.
I suggest to remove the CSV format entirely - it will be done in later classes.

**Comment by soungalo** [comment]
- In general, the lecture is too packed. Maybe move regex to another lecture.
- The file-parsing exercise is too integrative. Should be easier and more specific. Split to two exercises: one for writing files (optional) and one for writing a parser function.
- When teaching the regex syntax, show examples on natural text rather than DNA (too difficult to see why patterns are found/not found in DNA strings).
- Show how to parse files using regex.
