### ISSUE TITLE
Homework - beginning of course

### ISSUE THREAD

**Issue by yoavram** [yoavram/Py4Life#6]
- [x] 1
- [x] 2
- [x] 3
- [x] 4

**Comment by soungalo** [comment]
Wrote 4 questions for homework 1. Can you take a look?

**Comment by yoavram** [comment]
I think hw1 is very good.
I made some comments on the commit page: 6b20c265572d134ed9f3f547907ae8b1554d8947

**Comment by yoavram** [comment]
Also, I made a draft of [hw2](http://nbviewer.ipython.org/github/yoavram/Py4Life/blob/master/hw2.ipynb) you can comment in commit 4ef02fedec4c2791efecdc24c94065ca427e8f4f

**Comment by soungalo** [comment]
- [x] HW1 - i think it's almost complete, just have a look at the comments (commit 6d23886cf057dbb6d192664743fc97f82acbe73d).
- [x] HW2:
  - The splicing questions can be turned into one question with 3 parts.
  - The questions from python for bio - since there are full solutions, I think we'll have to give them some twist and change a bit...
  - The two last questions require file processing, which we only teach on lecture 4, so we can either give the data in the code or change the questions in another way.
- [x] Please review HW3

**Comment by yoavram** [comment]
- [x] HW 1: Made 2 comments in commit 6d23886cf057dbb6d192664743fc97f82acbe73d.

**Comment by soungalo** [comment]
Added hw4. Can you please review?

**Comment by yoavram** [comment]
reviewed hw3 and hw4, see pull requests #21 and #22

**Comment by yoavram** [comment]
@soungalo please have a look at hw2 - I'm waiting to get the data for the questions (long story) but otherwise it is ready in commit 4d9c458.

**Comment by soungalo** [comment]
Very nice exercises. Two notes:
question 2 - since there is no file involved, the title should be changed.
question 3 - it is not clear enough whether the numbers in _exons_ list represent positions in DNA or indexes in the string. Maybe add a sentence to clear out any possible confusions.
I have also solved the questions.
